


import Header from "@/components/Header/header";
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'


const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>vintph16172-NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>

      </main>
        

      <footer >
        
      </footer>
    </div>
  )
}

export default Home
